### ISSUE TITLE
Socket Timeout & incorrect error handling

### ISSUE THREAD

**Issue by rocketinventor** [GatoLoko/Wattpad2Epub#16]
The program has a timeout error on the SSL handshake and that error causes more errors because it is not caught correctly. See (partially redacted) logs below:

Entered command: ```D:\DOWNLO~1\WATTPA~1>WATTPA~1.PY https://www.wattpad.com/story/185706320-earthshine-the-raintree-chronicles-book-1```

```
b"'Earthshine: The Raintree Chronicles Book 1' by grahambower"
https://a.wattpad.com/cover/185706320-352-k381040.jpg
b'Working on: 1. When the student is ready'
Current url: http://www.wattpad.com/725708244-earthshine-the-raintree-chronicles-book-1-1-when
Pages in this chapter: 3


... ... ...


b'Working on: 3. The party'
Current url: http://www.wattpad.com/727354183-earthshine-the-raintree-chronicles-book-1-3-the
Pages in this chapter: 6
Working on: http://www.wattpad.com/727354183-earthshine-the-raintree-chronicles-book-1-3-the/page/1
Working on: http://www.wattpad.com/727354183-earthshine-the-raintree-chronicles-book-1-3-the/page/2
Working on: http://www.wattpad.com/727354183-earthshine-the-raintree-chronicles-book-1-3-the/page/3
Working on: http://www.wattpad.com/727354183-earthshine-the-raintree-chronicles-book-1-3-the/page/4
Working on: http://www.wattpad.com/727354183-earthshine-the-raintree-chronicles-book-1-3-the/page/5
Working on: http://www.wattpad.com/727354183-earthshine-the-raintree-chronicles-book-1-3-the/page/6
b'Working on: 4. The first incursion'
Current url: http://www.wattpad.com/731927539-earthshine-the-raintree-chronicles-book-1-4-the
Pages in this chapter: 5
Working on: http://www.wattpad.com/731927539-earthshine-the-raintree-chronicles-book-1-4-the/page/1
Working on: http://www.wattpad.com/731927539-earthshine-the-raintree-chronicles-book-1-4-the/page/2
Working on: http://www.wattpad.com/731927539-earthshine-the-raintree-chronicles-book-1-4-the/page/3
Traceback (most recent call last):
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1414, in connect
    server_hostname=server_hostname)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1059: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DOWNLO~1\WATTPA~1\wattpad2epub.py", line 285, in <module>
    get_book(args.initial_url[0])
  File "D:\DOWNLO~1\WATTPA~1\wattpad2epub.py", line 241, in get_book
    chapter = get_chapter("{}{}".format(base_url, item['href']))
  File "D:\DOWNLO~1\WATTPA~1\wattpad2epub.py", line 145, in get_chapter
    for j in get_page(page_url):
  File "D:\DOWNLO~1\WATTPA~1\wattpad2epub.py", line 128, in get_page
    text = get_html(text_url).select('pre')
  File "D:\DOWNLO~1\WATTPA~1\wattpad2epub.py", line 65, in get_html
    request = urllib.request.urlopen(req)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\prime\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error _ssl.c:1059: The handshake operation timed out>
```

**Comment by GatoLoko** [comment]
Since there are no further comments since my attempt to fix this nine month ago, I will assume it worked.
