### ISSUE TITLE
No downloading URL with latin characters such as í á ó à, etc.

### ISSUE THREAD

**Issue by hael33** [GatoLoko/Wattpad2Epub#35]
Hi, I am know to github and programming in general. Manage to install and play this wonderful project, but just with URL and books written in english. When I tried to download books wich are in portuguese, the above message appears. Thankyou for this amazing git!:

asus@asus-K46CA:~/wattpadscraper/Wattpad2Epub-master$ python3 wattpad2epub.py https://www.wattpad.com/903426169-percy-jackson-filho-de-voldemort-capítulo-1
Traceback (most recent call last):
  File "wattpad2epub.py", line 211, in <module>
    get_book(args.initial_url[0])
  File "wattpad2epub.py", line 115, in get_book
    html = gsweb.get_soup(initial_url)
  File "/home/asus/wattpadscraper/Wattpad2Epub-master/libs/gsweb.py", line 77, in get_soup
    html = get_url(url)
  File "/home/asus/wattpadscraper/Wattpad2Epub-master/libs/gsweb.py", line 51, in get_url
    response = urllib.request.urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1292, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.6/http/client.py", line 1140, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xed' in position 51: ordinal not in range(128)

**Comment by GatoLoko** [comment]
I'd like to test this, but the URL given by the opener does no longer exist. Anybody knows another similar case?

**Comment by GatoLoko** [comment]
Found a book with tildes in the URLs and tested it. It's working now.
