### ISSUE TITLE
AttributeError at the end of the prosses

### ISSUE THREAD

**Issue by vbonnal** [GatoLoko/Wattpad2Epub#7]
Hi,
At the end of the script (I'm using python 3.6 with Windows 7), I have an error "AttributeError: 'bytes' object has no attribute 'encode'".
I try also with your own example, there isi the same issue... I think it should be an error in the usage of the ebooklib library...
> (...)
Pages in this chapter: 3
Working on: http://www.wattpad.com/464522910-asylum-chapitre-40/page/1
Working on: http://www.wattpad.com/464522910-asylum-chapitre-40/page/2
Working on: http://www.wattpad.com/464522910-asylum-chapitre-40/page/3
Working on: Chapitre 41
Current url: http://www.wattpad.com/464524707-asylum-chapitre-41
Pages in this chapter: 2
Working on: http://www.wattpad.com/464524707-asylum-chapitre-41/page/1
Working on: http://www.wattpad.com/464524707-asylum-chapitre-41/page/2
Traceback (most recent call last):
  File "D:\Téléchargements\Wattpad2Epub-master\wattpad2epub.py", line 261, in <m
odule>
    get_book(args.initial_url[0])
  File "D:\Téléchargements\Wattpad2Epub-master\wattpad2epub.py", line 239, in ge
t_book
    epub.write_epub(epubfile, book, {})
  File "C:\Python36\lib\site-packages\ebooklib\epub.py", line 1534, in write_epu
b
    epub.write()
  File "C:\Python36\lib\site-packages\ebooklib\epub.py", line 1224, in write
    self._write_items()
  File "C:\Python36\lib\site-packages\ebooklib\epub.py", line 1213, in _write_it
ems
    self.out.writestr('%s/%s' % (self.book.FOLDER_NAME, item.file_name), item.ge
t_content())
  File "C:\Python36\lib\site-packages\ebooklib\epub.py", line 453, in get_conten
t
    self.content = self.book.get_template('cover')
  File "D:\Téléchargements\Wattpad2Epub-master\wattpad2epub.py", line 106, in ne
w_get_template
    return original_get_template(*args, **kwargs).encode(encoding='utf8')
AttributeError: 'bytes' object has no attribute 'encode'
>

**Comment by GatoLoko** [comment]
This is caused by changes in the new ebooklib 0.16 release.

With previous releases a workaround (lines 94 to 107) was necessary for a bug in ebooklib. The new release fixes the bug, and conflicts with the workaround.

I've just commited a patch that should fix it.

**Comment by vbonnal** [comment]
Ok, thanks a lot, It's fine now. I try it and I obtain a epub ! Good job ;-)
